import type { Metadata } from "next";
import { Geist, Geist_Mono, Bebas_Neue, Anton, Montserrat, Playfair_Display } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  weight: "400",
  variable: "--font-bebas-neue",
  subsets: ["latin"],
});

const anton = Anton({
  weight: "400",
  variable: "--font-anton",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: "300",
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  weight: ["700", "900"],
  style: ["italic"],
  variable: "--font-playfair",
  subsets: ["latin"],
});

const personaFont = localFont({
  src: "../public/fonts/persona.ttf",
  variable: "--font-persona",
  display: "swap",
});

const skipFont = localFont({
  src: "../public/fonts/FOT-Skip Std B.otf",
  variable: "--font-skip",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable} ${anton.variable} ${montserrat.variable} ${playfairDisplay.variable} ${personaFont.variable} ${skipFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

